# Generated by Django 4.2.10 on 2024-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
