# Generated by Django 4.2.10 on 2024-02-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='members')),
                ('designation', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
